steps:
    - label: ":shipit: Deploy the Thing :tm: "
      command: ./vault/scripts/deploy.sh
      plugins:
        - vault-secrets#v2.2.0:
            server: "http://localhost:8200"
            path: secret/buildkite
            auth:
              method: "approle"
              role-id: "${VAULT_ROLE_ID}"

    - wait

    - label: ":shipit: Get secret from mountpath kv/ :tm: "
      command: ./vault/scripts/secret.sh
      plugins:
        - vault-secrets#v2.2.0:
            server: "http://localhost:8200"
            path: kv/buildkite
            auth:
              method: "approle"
              role-id: "${VAULT_ROLE_ID}"

    - wait

    - label: ":vault: :bomb: clean up"
      command: docker compose -f ./vault/docker-compose.yml down