steps:
  - label: "default"
    command: buildkite-agent annotate "default" --context "default"

  - wait:

  - label: "info"
    command: buildkite-agent annotate "info" --style "info" --context "info"

  - wait:

  - label: "success"
    command: buildkite-agent annotate "success" --style "success" --context "success"

  - wait:

  - label: "warning"
    command: buildkite-agent annotate "warning" --style "warning" --context "warning"

  - wait:

  - label: "error"
    command: buildkite-agent annotate "error" --style "error" --context "error"

  - label: "surprise"
    command: |
      buildkite-agent annotate "<img class="emoji" title="one-does-not-simply" alt=":one-does-not-simply:" src="https://buildkiteassets.com/emojis/img-buildkite-64/one-does-not-simply.png" draggable="false" /> One does not simply annotate." --style "success"